[theme]
base = "dark"
primaryColor = "#DDB6F2"              # Pastel purple (soft, modern)
backgroundColor = "#1E1E2E"           # Deep bluish-purple (for dark mode)
secondaryBackgroundColor = "#2A263D"  # Slightly lighter cards/boxes
textColor = "#F8F8F2"                 # Off-white text for smooth contrast
font = "sans serif"
