[theme]
base = "dark"
primaryColor = "#A259FF"              # Vibrant purple
backgroundColor = "#1E1B2E"           # Very dark purple-ish background
secondaryBackgroundColor = "#2D2840"  # Slightly lighter secondary background
textColor = "#FFFFFF"                 # Clean white text
font = "sans serif"                   # Clean, modern look

