[theme]
primaryColor = "#9D4EDD"               # Soft royal purple
backgroundColor = "#F8F5FF"            # Very light lavender background
secondaryBackgroundColor = "#EDE9F7"   # Slight contrast for sidebar/cards
textColor = "#2D2A35"                  # Deep gray text for readability
font = "monospace"

